services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
