services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - tictactoe-network
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - tictactoe-network
    depends_on:
      - backend

networks:
  tictactoe-network:
    driver: bridge
